# Generated by Django 4.2.4 on 2023-09-19 22:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numAttempts', models.PositiveIntegerField(default=15)),
                ('numQuestions', models.PositiveIntegerField(default=10)),
                ('dueDate', models.DateTimeField(default=datetime.datetime(2023, 10, 3, 22, 24, 43, 892091, tzinfo=datetime.timezone.utc))),
            ],
        ),
        migrations.CreateModel(
            name='GeneratedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('marks', models.PositiveIntegerField()),
                ('level', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SubmitAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('level', models.TextField()),
                ('expectedQuery', models.JSONField()),
                ('userQuery', models.JSONField()),
                ('mark', models.PositiveIntegerField()),
                ('status', models.TextField()),
            ],
            options={
                'verbose_name': 'Submtted Assignment',
                'verbose_name_plural': 'Submtted Assignment',
                'unique_together': {('question', 'level', 'expectedQuery', 'userQuery', 'mark', 'status')},
            },
        ),
        migrations.CreateModel(
            name='IntermediateSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('marks', models.IntegerField(default=3)),
            ],
            options={
                'verbose_name': 'Intermediate Questions',
                'verbose_name_plural': 'Intermediate Questions',
                'unique_together': {('question', 'answer', 'marks')},
            },
        ),
        migrations.CreateModel(
            name='Gradebook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numTemps', models.IntegerField(default=0)),
                ('overallMarks', models.FloatField(default=0)),
                ('studentNum', models.IntegerField(default=0)),
                ('easy', models.IntegerField(default=0)),
                ('intermediate', models.IntegerField(default=0)),
                ('hard', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Gradebook',
                'verbose_name_plural': 'Gradebook',
            },
        ),
        migrations.CreateModel(
            name='BasicSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('marks', models.IntegerField(default=2)),
            ],
            options={
                'verbose_name': 'Basic Questions',
                'verbose_name_plural': 'Basic Questions',
                'unique_together': {('question', 'answer', 'marks')},
            },
        ),
        migrations.CreateModel(
            name='AdvancedSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
                ('marks', models.IntegerField(default=4)),
            ],
            options={
                'verbose_name': 'Advanced Questions',
                'verbose_name_plural': 'Advanced Questions',
                'unique_together': {('question', 'answer', 'marks')},
            },
        ),
    ]
