# Generated by Django 4.2.4 on 2023-09-19 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignmentsettings',
            name='dueDate',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 3, 22, 25, 9, 374223, tzinfo=datetime.timezone.utc)),
        ),
    ]
